openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1:8000'
paths:
  /api/login:
    post:
      summary: 'Login Api.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'User email.'
                  example: superadmin@invoke.com
                password:
                  type: string
                  description: 'User password.'
                  example: password
                user_id:
                  type: integer
                  description: 'optional The id of the user.'
                  example: 9
              required:
                - email
                - password
      security: []
  /api/dashboard:
    post:
      summary: Dashboard.
      description: 'Requires Bearer Token in order to display the user count.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {{token}}'
          schema:
            type: string
      responses:
        401:
          description: 'invalid token'
          content:
            text/plain:
              schema:
                type: string
                example: ''
      tags:
        - Endpoints
  /api/users:
    post:
      summary: 'Display Users API.'
      description: 'Get all users by pagination'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {{token}}'
          schema:
            type: string
      responses:
        401:
          description: 'invalid token'
          content:
            text/plain:
              schema:
                type: string
                example: ''
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                  description: 'optional Page number for pagination.'
                  example: 1
tags:
  -
    name: Endpoints
    description: ''
